---
title: "case_study"
author: "Martha Mulugeta"
date: "10/8/2019"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridis)
library(leaflet)
knitr::opts_chunk$set(
	echo = TRUE,
	warning = FALSE,
	fig.width = 8, 
  fig.height = 6,
  out.width = "90%"
)
options(
  ggplot2.continuous.colour = "viridis",
  ggplot2.continuous.fill = "viridis"
)
scale_colour_discrete = scale_colour_viridis_d
scale_fill_discrete = scale_fill_viridis_d
theme_set(theme_minimal() + theme(legend.position = "bottom"))
```

```{r}
knitr::opts_chunk$set(echo = TRUE)

library(p8105.datasets)
data(nyc_airbnb)
```

* how are air bnb prices related to rent in the neighborhood?
* which neighborhood is most expensive and which is cheapest?
* do hosts with multiple sites have higher prices or ratings? 
* does price have any relation to ratings? 
* is average length of stay related to neighborhood? price? etc? 

```{r}
nyc_airbnb =
nyc_airbnb %>% 
  mutate(
    stars = review_scores_location / 2,
    borough = neighbourhood_group
  )
```

```{r}
nyc_airbnb %>%
 mutate(neighbourhood = as.factor(neighbourhood)) %>%
  filter(borough == "Manhattan") %>% 
  mutate(neighbourhood = fct_reorder(neighbourhood, price, na.rm = TRUE)) %>% 
 ggplot(aes(x = price, y = neighbourhood)) +
 geom_violin()
```

```{r}
price_neighborhood = 
  select(nyc_airbnb,neighbourhood, price) %>%
  group_by(neighbourhood) %>%
  summarise(
   mean_price = mean(price)
 ) %>%
 arrange(
   -mean_price
 )
```

```{r}
nyc_airbnb %>%
  janitor::clean_names() %>% 
  select(price, neighbourhood_group) %>% 
  arrange(desc(price))
```

```{r}
nyc_airbnb %>% 
  group_by(borough, room_type) %>% 
  summarize(med_price = median(price, na.rm = TRUE)) %>% 
  pivot_wider(
    names_from = room_type,
    values_from = med_price
  )
```

```{r}
nyc_airbnb %>% 
  filter(borough == "Staten Island", room_type == "Shared room")
```

```{r}
nyc_airbnb %>% 
  count(borough, room_type) %>% 
  pivot_wider(
    names_from = room_type,
    values_from = n
  )
```

```{r}
nyc_airbnb %>%
 group_by(neighbourhood_group, neighbourhood) %>%
 summarize(
   mean_price = mean(price, na.rm = TRUE),
   mean_review = mean(review_scores_location, na.rm = TRUE)
 ) %>% 
  ggplot(aes(x = mean_review, y = mean_price)) +
  geom_point() +
  facet_grid(~neighbourhood_group)
```

```{r}
nyc_airbnb %>% 
  count(neighbourhood)
```

```{r}
nyc_airbnb %>%
  filter(neighbourhood == "Astoria") %>% 
  ggplot(aes(x = stars, y = price)) +
  geom_point() 
```

```{r}
nyc_airbnb %>% 
  filter(borough == "Manhattan",
         price < 1000) %>% 
  ggplot(aes(x = lat, y = long, color = price)) +
  geom_point(alpha = 0.3) +
  facet_grid(~room_type)
```
```{r}
nyc_airbnb %>%
  filter(
    borough == "Manhattan",
    price > 2000) %>% 
  leaflet() %>% 
  addTiles() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addCircleMarkers(
    ~lat, ~long, 
    radius = 1)
```

```{r}
pal <- colorNumeric(
  palette = "viridis",
  domain = nyc_airbnb$stars)  

nyc_airbnb %>%
  filter(
    borough == "Manhattan") %>% 
    mutate(
      label = str_c("<b>Stars: ", stars, "<b><b>Price: ", price , sep = "")
    ) %>% 
  sample_n(5000) %>% 
  leaflet() %>% 
  addTiles() %>% 
  addProviderTiles(providers$CartoDB.Positron) %>% 
  addCircleMarkers(
    ~lat, ~long, 
    color = ~pal(stars),
    radius = 1)
```









